name: 'databricks_demo'
version: '2.0.0'
config-version: 2

dbt-cloud: 
    project-id: 12985

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
# analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["docs"]
snapshot-paths: ["snapshots"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-start: "grant usage on schema {{target.database}}.{{target.schema}} to `Partner Engineers`"

flags:
  require_generic_test_arguments_property: true
  use_materialization_v2: true
  use_managed_iceberg: true

models:
  databricks_demo:
    # persist resource descriptions as column and relation comments in Unity Catalog
    +persist_docs:
      relation: true
      columns: true
    # Applies to all files under models/example/
    +file_format: delta
    
    # Iceberg support
    # +table_formate: icberg 
    # Whether or not to provision Iceberg compatibility for the materialization
    
    # Databricks Tags
    # +databricks_tags: {'my_tag': 'my_value'}
    # Tags to be set on the created table
    +incremental_strategy: merge
    staging:
      +schema: stage
      +group: data-engineering
      +materialized: view
      +access: protected # Options: private | public | protected
      intermediate:
        +schema: intermediate
    marts:
      +schema: marts
      +materialized: table
      +group: analytics
        
    
